# Generated by Django 3.2.12 on 2023-09-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='estado',
            new_name='status',
        ),
    ]
