# Generated by Django 3.2.12 on 2023-09-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_rename_estado_entrada_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='status',
            new_name='estado',
        ),
    ]
