# Generated by Django 3.2.12 on 2023-09-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_rename_status_entrada_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada',
            new_name='CalendarioModel',
        ),
    ]
