# Generated by Django 3.2.12 on 2023-01-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('tel_number', models.IntegerField(max_length=15)),
                ('addres', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=240)),
                ('bio', models.TextField(max_length=300)),
                ('picture', models.ImageField(upload_to='media/agenda')),
            ],
        ),
    ]
