# Generated by Django 3.2.12 on 2023-01-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamodel',
            name='tel_number',
            field=models.IntegerField(),
        ),
    ]
