# Generated by Django 3.2.12 on 2023-08-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0002_alter_agendamodel_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamodel',
            name='picture',
            field=models.ImageField(upload_to='agenda'),
        ),
    ]
