# Generated by Django 3.2.12 on 2023-06-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasApp', '0003_notasmodel_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasmodel',
            options={'verbose_name': 'nota', 'verbose_name_plural': 'notas'},
        ),
    ]
