# Generated by Django 3.2.12 on 2023-07-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notasApp', '0004_alter_notasmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasmodel',
            name='fecha_edicion',
        ),
    ]
