# Generated by Django 3.2.12 on 2023-08-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
